platform :ios, '7.0'

link_with ['GameTime', 'Specs']

pod 'LXReorderableCollectionViewFlowLayout', '~> 0.1'
pod 'CocoaLumberjack', '~> 1.8'
pod 'InfColorPicker', '~> 0.0.1'
pod 'SDColor', '~> 0.1'

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Pods-Acknowledgements.plist', 'GameTime/Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end

target :Specs do
    pod 'Cedar', '~> 0.9.4'
	pod 'Expecta', '~> 0.2.3'
	pod 'OCMock', '~> 2.2.2'
end